name: flutter_bgthread
description: Easier parallelism for dart flutter apps.
version: 0.0.1
repository: https://github.com/willp/flutter_bgthread

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.5
dependencies:
  flutter:
    sdk: flutter
